
-- USE TREE_MONITOR;
-- SELECT * FROM TREE_STATE;
-- -- ________________________________________
-- CREATE DATABASE BAIDOXE;

-- USE BAIDOXE;


-- CREATE TABLE THE (
-- 	MATHE char(6),
--     DANGSUDUNG varchar(7),
--     CONSTRAINT PK_THE PRIMARY KEY(MATHE),
--     CONSTRAINT CK_THE_DANGSUDUNG CHECK (DANGSUDUNG IN ('USE', 'NOTUSE'))
-- );



-- CREATE TABLE XEVAO (
-- 	MATHE char(6),
--     GIOVAO datetime,
--     BIENSOXE varchar(11),
--     IMAGE varchar(50),
--     CONSTRAINT PK_XEVAO PRIMARY KEY(MATHE, GIOVAO),
--     CONSTRAINT FK_XEVAO_MATHE FOREIGN KEY(MATHE) REFERENCES THE(MATHE)
-- );



-- CREATE TABLE XERA (
-- 	MATHE char(6),
--     GIORA datetime,
--     BIENSOXE varchar(11),
--     IMAGE varchar(50),
--     CONSTRAINT PK_XERA PRIMARY KEY(MATHE, GIORA),
--     CONSTRAINT FK_XERA_MATHE FOREIGN KEY(MATHE) REFERENCES THE(MATHE)
-- );

-- DROP TABLE XERA;
-- DROP TABLE XEVAO;
-- DROP TABLE THE;


-- INSERT INTO THE VALUES ("000000", "NOTUSE");
-- INSERT INTO THE VALUES ("000001", "NOTUSE");
-- INSERT INTO THE VALUES ("000002", "NOTUSE");
-- INSERT INTO THE VALUES ("000003", "NOTUSE");
-- INSERT INTO THE VALUES ("000004", "NOTUSE");

-- SELECT * FROM XEVAO;

CREATE DATABASE CAR_PARKING;

USE CAR_PARKING;

CREATE TABLE CARD (
	CARDID varchar(10),
    INUSE varchar(7),
    CONSTRAINT PK_CARD PRIMARY KEY(CARDID),
    CONSTRAINT CK_CARD_INUSE CHECK (INUSE IN ('USE', 'NOTUSE'))
);

CREATE TABLE PARKING (
	PARKINGID varchar(20),
	NUMBERPLATE varchar(15),
    CARDID varchar(10),
    TIMEIN datetime,
    TIMEOUT datetime,
    IMAGEIN varchar(50),
    IMAGEOUT varchar(50),
    STATE varchar(10),
    CONSTRAINT PK_PARKING PRIMARY KEY(PARKINGID),
    CONSTRAINT FK_PARKING_CARDID FOREIGN KEY(CARDID) REFERENCES CARD(CARDID),
    CONSTRAINT CK_PARKING_CARDID CHECK(STATE IN ("PARKING","DONE"))
);
DROP TABLE CARD;
DROP TABLE PARKING;

SELECT * FROM PARKING;
SELECT * FROM CARD;

-- DELETE FROM PARKING;
-- DELETE FROM CARD;


INSERT INTO CARD VALUES("0A134A6437","NOTUSE");
INSERT INTO CARD VALUES("9A23486495","NOTUSE");
INSERT INTO CARD VALUES("00A503B645","NOTUSE");
INSERT INTO CARD VALUES("A1BFE41BE1","NOTUSE");
INSERT INTO CARD VALUES("043DC4971D","NOTUSE");

